//! `weaft init` — scaffold a new weaft project directory.

use super::write_file;
use miette::{IntoDiagnostic, miette};
use std::path::{Path, PathBuf};
use std::process::ExitCode;
use weaft_core::capability;

#[derive(clap::Args)]
pub struct Args {
    /// Project name; also the directory created.
    pub name: String,
    /// Prefill `targets.supported` (repeatable). Default: claude-code, cursor.
    #[arg(long = "target")]
    pub targets: Vec<String>,
    /// Parent directory in which to create the project.
    #[arg(long, default_value = ".")]
    pub path: PathBuf,
    /// Scaffold only `weaft.yaml` + one skill (no parameters, fragments, or subagent).
    #[arg(long)]
    pub minimal: bool,
}

pub fn run(args: &Args) -> miette::Result<ExitCode> {
    let root = args.path.join(&args.name);
    if root.exists() && std::fs::read_dir(&root).is_ok_and(|mut d| d.next().is_some()) {
        return Err(miette!(
            "{} already exists and is not empty",
            root.display()
        ));
    }
    std::fs::create_dir_all(&root).into_diagnostic()?;

    // Default to the registry's init-default set (claude-code + cursor) rather than a hardcoded
    // literal, so the scaffolded `targets.supported` follows the capability matrix (C-REGISTRY).
    let targets = if args.targets.is_empty() {
        capability::init_default_ids()
            .into_iter()
            .map(str::to_string)
            .collect()
    } else {
        args.targets.clone()
    };

    write_file(
        &root,
        Path::new("weaft.yaml"),
        manifest(&args.name, &targets, args.minimal).as_bytes(),
    )?;
    write_file(
        &root,
        Path::new("skills/hello.md"),
        hello_skill(args.minimal).as_bytes(),
    )?;

    if !args.minimal {
        write_file(
            &root,
            Path::new("agents/reviewer.md"),
            reviewer_agent().as_bytes(),
        )?;
        write_file(
            &root,
            Path::new("fragments/footer.md.j2"),
            FOOTER_FRAGMENT.as_bytes(),
        )?;
    }

    eprintln!("created weaft project at {}", root.display());
    eprintln!("  next: weaft build --manifest-path {}", root.display());
    Ok(ExitCode::SUCCESS)
}

fn manifest(name: &str, targets: &[String], minimal: bool) -> String {
    use std::fmt::Write as _;
    let supported = targets.iter().fold(String::new(), |mut acc, t| {
        let _ = writeln!(acc, "    - {t}");
        acc
    });
    let params = if minimal {
        String::new()
    } else {
        format!(
            "\nparameters:\n  project_name:\n    type: string\n    default: {name}\n    description: Name injected into rendered bodies.\n"
        )
    };
    format!(
        "name: {name}\nversion: 0.1.0\ndescription: A weaft project.\n\ntargets:\n  supported:\n{supported}{params}\nmeta:\n  authors: []\n  tags: []\n"
    )
}

fn hello_skill(minimal: bool) -> String {
    let footer = if minimal {
        ""
    } else {
        "\n{% include \"fragments/footer.md.j2\" %}\n"
    };
    format!(
        "---\nname: hello\ndescription: A starter skill that greets and orients the agent.\n---\n# Hello from {{{{ project.name }}}}\n\nYou are running under **{{{{ host.display_name }}}}**.\n\n## Example\nWhen asked to say hello, greet the user and name the current host.\n{footer}"
    )
}

fn reviewer_agent() -> String {
    // Same source, capability-aware: Claude emits `tools:`, Cursor emits `readonly:`.
    "---\nname: reviewer\ndescription: Reviews code changes for correctness and clarity. Use after writing code.\ntools:\n  - Read\n  - Grep\nmodel: inherit\nreadonly: true\n---\nYou are a meticulous code reviewer for {{ project.name }}.\n\n{% if host.agent_supports_tools %}You may use only these tools: {{ agent.tools | join(\", \") }}.{% else %}You operate in read-only mode and never modify files.{% endif %}\n\n## Example\nGiven a diff, list issues grouped by severity (critical, high, medium).\n"
        .to_string()
}

const FOOTER_FRAGMENT: &str = "\n---\n_Generated by weaft for {{ host.display_name }}._\n";
